apiVersion: v1
kind: Service
metadata:
  name: uas-tool
  labels:
    app: uas-tool
spec:
  type: ClusterIP
  selector:
    app: uas-tool
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
